'use strict';

export const START_ACTION = `START_ACTION`;
export const STOP_ACTION = `STOP_ACTION`;
export const REFRESH_START_ACTION = `REFRESH_START_ACTION`;
export const REFRESH_STOP_ACTION = `REFRESH_STOP_ACTION`;
